In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\tobin\Downloads\world_population.csv")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [7]:
df = pd.read_csv(r"C:\Users\tobin\Downloads\world_population.csv", index_col = "Country")
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [24]:
df.reset_index(inplace=True)

In [13]:

df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [15]:
df.set_index('Country', inplace = True)
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [16]:
df.loc['Albania']

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [17]:
df.iloc[1]

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [25]:
df.set_index(['Continent','Country'], inplace = True)
df

                             index  Rank CCA3           Capital  \
Continent Country
Asia      Afghanistan            0    36  AFG             Kabul
Europe    Albania                1   138  ALB            Tirana
Africa    Algeria                2    34  DZA           Algiers
Oceania   American Samoa         3   213  ASM         Pago Pago
Europe    Andorra                4   203  AND  Andorra la Vella
...                            ...   ...  ...               ...
Oceania   Wallis and Futuna    229   226  WLF          Mata-Utu
Africa    Western Sahara       230   172  ESH          El Aaiún
Asia      Yemen                231    46  YEM             Sanaa
Africa    Zambia               232    63  ZMB            Lusaka
          Zimbabwe             233    74  ZWE            Harare

                             2022 Population  2020 Population  \
Continent Country
Asia      Afghanistan             41128771.0       38972230.0
Europe    Albania                  2842321.0        2866849.0
Africa    Algeria                 44903225.0       43451666.0
Oceania   American Samoa             44273.0          46189.0
Europe    Andorra                    79824.0          77700.0
...                                      ...              ...
Oceania   Wallis and Futuna          11572.0          11655.0
Africa    Western Sahara            575986.0         556048.0
Asia      Yemen                   33696614.0       32284046.0
Africa    Zambia                  20017675.0       18927715.0
          Zimbabwe                16320537.0       15669666.0

                             2015 Population  2010 Population  \
Continent Country
Asia      Afghanistan             33753499.0       28189672.0
Europe    Albania                  2882481.0        2913399.0
Africa    Algeria                 39543154.0       35856344.0
Oceania   American Samoa             51368.0          54849.0
Europe    Andorra                    71746.0          71519.0
...                                      ...              ...
Oceania   Wallis and Futuna          12182.0          13142.0
Africa    Western Sahara            491824.0         413296.0
Asia      Yemen                   28516545.0       24743946.0
Africa    Zambia                         NaN       13792086.0
          Zimbabwe                14154937.0       12839771.0

                             2000 Population  1990 Population  \
Continent Country
Asia      Afghanistan             19542982.0       10694796.0
Europe    Albania                  3182021.0        3295066.0
Africa    Algeria                 30774621.0       25518074.0
Oceania   American Samoa             58230.0          47818.0
Europe    Andorra                    66097.0          53569.0
...                                      ...              ...
Oceania   Wallis and Futuna          14723.0          13454.0
Africa    Western Sahara            270375.0         178529.0
Asia      Yemen                   18628700.0       13375121.0
Africa    Zambia                   9891136.0        7686401.0
          Zimbabwe                11834676.0       10113893.0

                             1980 Population  1970 Population  Area (km²)  \
Continent Country
Asia      Afghanistan             12486631.0       10752971.0    652230.0
Europe    Albania                  2941651.0        2324731.0     28748.0
Africa    Algeria                 18739378.0       13795915.0   2381741.0
Oceania   American Samoa             32886.0          27075.0       199.0
Europe    Andorra                    35611.0          19860.0       468.0
...                                      ...              ...         ...
Oceania   Wallis and Futuna          11315.0           9377.0       142.0
Africa    Western Sahara            116775.0          76371.0    266000.0
Asia      Yemen                    9204938.0        6843607.0    527968.0
Africa    Zambia                   5720438.0        4281671.0    752612.0
          Zimbabwe                 7049926.0        5202918.0    390757.0

                             Density (per km²)  Growth Rate  \
Continent Country
Asia      Afghanistan                  63.0587       1.0257
Europe    Albania                      98.8702       0.9957
Africa    Algeria                      18.8531       1.0164
Oceania   American Samoa              222.4774       0.9831
Europe    Andorra                     170.5641       1.0100
...                                        ...          ...
Oceania   Wallis and Futuna            81.4930       0.9953
Africa    Western Sahara                2.1654       1.0184
Asia      Yemen                        63.8232       1.0217
Africa    Zambia                       26.5976       1.0280
          Zimbabwe                     41.7665       1.0204

                             World Population Percentage
Continent Country
Asia      Afghanistan                               0.52
Europe    Albania                                   0.04
Africa    Algeria                                   0.56
Oceania   American Samoa                            0.00
Europe    Andorra                                   0.00
...                                                  ...
Oceania   Wallis and Futuna                         0.00
Africa    Western Sahara                            0.01
Asia      Yemen                                     0.42
Africa    Zambia                                    0.25
          Zimbabwe                                  0.20

[234 rows x 16 columns]

In [19]:
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [31]:
df.sort_index()
#pd.set_option('display.max.columns',235)

                            index  Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria           2    34  DZA      Algiers       44903225.0
              Angola            5    42  AGO       Luanda       35588987.0
              Benin            21    77  BEN   Porto-Novo       13352864.0
              Botswana         26   144  BWA     Gaborone        2630296.0
              Burkina Faso     31    58  BFA  Ouagadougou       22673762.0
...                           ...   ...  ...          ...              ...
South America Paraguay        161   109  PRY     Asunción        6780744.0
              Peru            162    44  PER         Lima       34049588.0
              Suriname        199   170  SUR   Paramaribo         618040.0
              Uruguay         223   133  URY   Montevideo        3422794.0
              Venezuela       227    51  VEN      Caracas       28301696.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria            43451666.0       39543154.0       35856344.0
              Angola             33428485.0       28127721.0       23364185.0
              Benin              12643123.0       10932783.0        9445710.0
              Botswana            2546402.0        2305171.0        2091664.0
              Burkina Faso       21522626.0       18718019.0       16116845.0
...                                     ...              ...              ...
South America Paraguay            6618695.0        6177950.0        5768613.0
              Peru               33304756.0       30711863.0       29229572.0
              Suriname             607065.0         575475.0         546080.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Venezuela          28490453.0       30529716.0       28715022.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria            30774621.0       25518074.0       18739378.0
              Angola             16394062.0       11828638.0        8330047.0
              Benin               6998023.0        5133419.0        3833939.0
              Botswana            1726985.0        1341474.0         938578.0
              Burkina Faso       11882888.0        9131361.0        6932967.0
...                                     ...              ...              ...
South America Paraguay            5123819.0        4059195.0        3078912.0
              Peru               26654439.0       22109099.0       17492406.0
              Suriname             478998.0         412756.0         375112.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Venezuela                 NaN       19750579.0       15210443.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria            13795915.0   2381741.0            18.8531
              Angola              6029700.0   1246700.0            28.5466
              Benin               3023443.0    112622.0           118.5635
              Botswana             592244.0    582000.0             4.5194
              Burkina Faso        5611666.0    272967.0            83.0641
...                                     ...         ...                ...
South America Paraguay            2408787.0    406752.0            16.6705
              Peru               13562371.0   1285216.0            26.4933
              Suriname             379918.0    163820.0             3.7727
              Uruguay             2790265.0    181034.0            18.9069
              Venezuela          11355475.0         NaN            30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 16 columns]

In [29]:
df

                             index  Rank CCA3           Capital  \
Continent Country
Asia      Afghanistan            0    36  AFG             Kabul
Europe    Albania                1   138  ALB            Tirana
Africa    Algeria                2    34  DZA           Algiers
Oceania   American Samoa         3   213  ASM         Pago Pago
Europe    Andorra                4   203  AND  Andorra la Vella
...                            ...   ...  ...               ...
Oceania   Wallis and Futuna    229   226  WLF          Mata-Utu
Africa    Western Sahara       230   172  ESH          El Aaiún
Asia      Yemen                231    46  YEM             Sanaa
Africa    Zambia               232    63  ZMB            Lusaka
          Zimbabwe             233    74  ZWE            Harare

                             2022 Population  2020 Population  \
Continent Country
Asia      Afghanistan             41128771.0       38972230.0
Europe    Albania                  2842321.0        2866849.0
Africa    Algeria                 44903225.0       43451666.0
Oceania   American Samoa             44273.0          46189.0
Europe    Andorra                    79824.0          77700.0
...                                      ...              ...
Oceania   Wallis and Futuna          11572.0          11655.0
Africa    Western Sahara            575986.0         556048.0
Asia      Yemen                   33696614.0       32284046.0
Africa    Zambia                  20017675.0       18927715.0
          Zimbabwe                16320537.0       15669666.0

                             2015 Population  2010 Population  \
Continent Country
Asia      Afghanistan             33753499.0       28189672.0
Europe    Albania                  2882481.0        2913399.0
Africa    Algeria                 39543154.0       35856344.0
Oceania   American Samoa             51368.0          54849.0
Europe    Andorra                    71746.0          71519.0
...                                      ...              ...
Oceania   Wallis and Futuna          12182.0          13142.0
Africa    Western Sahara            491824.0         413296.0
Asia      Yemen                   28516545.0       24743946.0
Africa    Zambia                         NaN       13792086.0
          Zimbabwe                14154937.0       12839771.0

                             2000 Population  1990 Population  \
Continent Country
Asia      Afghanistan             19542982.0       10694796.0
Europe    Albania                  3182021.0        3295066.0
Africa    Algeria                 30774621.0       25518074.0
Oceania   American Samoa             58230.0          47818.0
Europe    Andorra                    66097.0          53569.0
...                                      ...              ...
Oceania   Wallis and Futuna          14723.0          13454.0
Africa    Western Sahara            270375.0         178529.0
Asia      Yemen                   18628700.0       13375121.0
Africa    Zambia                   9891136.0        7686401.0
          Zimbabwe                11834676.0       10113893.0

                             1980 Population  1970 Population  Area (km²)  \
Continent Country
Asia      Afghanistan             12486631.0       10752971.0    652230.0
Europe    Albania                  2941651.0        2324731.0     28748.0
Africa    Algeria                 18739378.0       13795915.0   2381741.0
Oceania   American Samoa             32886.0          27075.0       199.0
Europe    Andorra                    35611.0          19860.0       468.0
...                                      ...              ...         ...
Oceania   Wallis and Futuna          11315.0           9377.0       142.0
Africa    Western Sahara            116775.0          76371.0    266000.0
Asia      Yemen                    9204938.0        6843607.0    527968.0
Africa    Zambia                   5720438.0        4281671.0    752612.0
          Zimbabwe                 7049926.0        5202918.0    390757.0

                             Density (per km²)  Growth Rate  \
Continent Country
Asia      Afghanistan                  63.0587       1.0257
Europe    Albania                      98.8702       0.9957
Africa    Algeria                      18.8531       1.0164
Oceania   American Samoa              222.4774       0.9831
Europe    Andorra                     170.5641       1.0100
...                                        ...          ...
Oceania   Wallis and Futuna            81.4930       0.9953
Africa    Western Sahara                2.1654       1.0184
Asia      Yemen                        63.8232       1.0217
Africa    Zambia                       26.5976       1.0280
          Zimbabwe                     41.7665       1.0204

                             World Population Percentage
Continent Country
Asia      Afghanistan                               0.52
Europe    Albania                                   0.04
Africa    Algeria                                   0.56
Oceania   American Samoa                            0.00
Europe    Andorra                                   0.00
...                                                  ...
Oceania   Wallis and Futuna                         0.00
Africa    Western Sahara                            0.01
Asia      Yemen                                     0.42
Africa    Zambia                                    0.25
          Zimbabwe                                  0.20

[234 rows x 16 columns]

In [34]:
df.loc['Africa','Angola']

index                                   5
Rank                                   42
CCA3                                  AGO
Capital                            Luanda
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: (Africa, Angola), dtype: object